name: Cypress End-2-End Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1.4.3
      - name: Encode workers
        run: npm run encode:worker
      - name: Cypress tests
        if: success()
        uses: cypress-io/github-action@v2.2.6
        with:
          working-directory: example
          start: npm start
          wait-on: http://localhost:1234
